# Generated by Django 3.1.1 on 2021-04-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210417_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id_name', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id_name', models.TextField()),
                ('payment_date', models.IntegerField()),
                ('payment_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id_name', models.TextField()),
                ('workout_name', models.TextField()),
                ('workout_description', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='CheckIn',
            new_name='Journal',
        ),
        migrations.AddField(
            model_name='memberships',
            name='memberships_duration',
            field=models.IntegerField(default=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberships',
            name='memberships_payment',
            field=models.IntegerField(default=140),
            preserve_default=False,
        ),
    ]
