# Generated by Django 3.1.1 on 2021-04-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210417_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='person_id_name',
            new_name='email_name',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='instructor',
            new_name='instructor_name',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='person_id_name',
            new_name='memberships_id',
        ),
        migrations.RenameField(
            model_name='memberships',
            old_name='person_id_name',
            new_name='memberships_name',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='person_id_name',
            new_name='person_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='instructor',
            new_name='email_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='person_id_name',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='person_id_name',
        ),
        migrations.AddField(
            model_name='journal',
            name='workout_id',
            field=models.TextField(default=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='instructor_name',
            field=models.TextField(default=140),
            preserve_default=False,
        ),
    ]
