# Generated by Django 3.1.1 on 2021-04-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210421_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender_name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='gender_name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender_name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_number',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email_name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='instructor_name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='email_name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='first_name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='last_name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='phone_number',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='check_in_date',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='check_in_time',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='check_out_time',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='instructor_name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='memberships_id',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='workout_id',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='memberships',
            name='memberships_duration',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='memberships',
            name='memberships_name',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='memberships',
            name='memberships_payment',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='memberships',
            name='status_name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='person_name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_number',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='password_name',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_name',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
