# Generated by Django 3.1.1 on 2021-05-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210504_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='memberships_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
